### ISSUE TITLE
Connecting... forever...

### ISSUE THREAD

**Issue by krakrjak** [icfpcontest2017/lambda-duct#3] opened 2017-08-06 09:15 UTC
Using the status page I have identified some ports available for games. When trying to use them, ports `9000-9010` I continue to just get connection failed.

Can these be bugs in my program? I never see any messages from my punter... ideas on how to troubleshoot?

**Comment by dhil** [comment] 2017-08-06 09:28
There seem to be problems with those particular server (note 9000 is not a game server). It seems like they have stopped accepting connections. We'll be looking into it. Thanks for notifying us.

**Comment by krakrjak** [comment] 2017-08-06 09:48
Since the upgrade to v0.3 the situation has changed. It seems I always timeout when hunting a game.
```
$ lamduct --game-hostname punter.inf.ed.ac.uk --game-port 9007 --log-level 3 .stack-work/dist/x86_64-linux-nopie/Cabal-1.24.0.0/build/punter/punter
lamduct: main: Resolving punter.inf.ed.ac.uk...
lamduct: main: ... resolved to 129.215.197.1.
lamduct: main: Creating TCP connection...
lamduct: main: Connecting to punter.inf.ed.ac.uk:9007...
lamduct: main: Connection established.
lamduct: main: Handshaking with client...
lamduct: main: Invoking program /home/krakrjak/src/Icfp2017-junkfood/.stack-work/dist/x86_64-linux-nopie/Cabal-1.24.0.0/build/punter/punter...
lamduct: main: Changing working directory to: /home/krakrjak/src/Icfp2017-junkfood/.stack-work/dist/x86_64-linux-nopie/Cabal-1.24.0.0/build/punter...
lamduct: main: Changing working directory to: /home/krakrjak/src/Icfp2017-junkfood...
lamduct: main: Interacting with client...
lamduct: main: BIO: receiving.
error: client or server connection was dropped.
```

**Comment by dhil** [comment] 2017-08-06 10:13
It would seem that interaction with your client application fails. The `error: client or server connection was dropped` is caused by an attempt to read a closed file descriptor. In order to get a better handle on what is happening you can try writing some debug info from the client to `/dev/stderr`, and then invoke `lamduct` with `--client-instance-logfile /dev/stderr` (or some other file name).

**Comment by dhil** [comment] 2017-08-06 10:16
The original problem regarding connecting to servers in port range `9001-9010` appears to have been fixed now.

**Closed as completed by dhil** 2017-08-06 10:16 UTC
Labels: bug
